# -*- coding: utf-8 -*-
"""chrome_automation_using_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjtXP16zoNKHKILq-5EMhawubSXJyiCt
"""

import webbrowser as wb

def webauto():
  chrome_path = 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ,%s'
  URLS = (
      "stackoverflow.com",
      "gmail.com",
      "google.com",
      "youtube.com"
  )

  for url in URLS:
    print("opening : " +url)
    wb.get(chrome_path).open(url)

webauto()